// Read-only tour: routes are fixed application paths, never operational actions.
export const tourSteps = [
  { area: "Today", title: "Start with what needs attention", href: "/workspace/overview", items: ["Follow the next-action banner and review pending recommendations or recent assessments.", "Check closing status, incoming deliveries and expiring stock at a glance."], note: "This dashboard is a summary. The other areas are where you record changes." },
  { area: "Daily operations · Inventory", title: "Know what you have", href: "/workspace/inventory", items: ["Physical counts show staff observations, with batch quantities, count times and expiry dates.", "Estimates account for recorded sales and receipts through a selected time. Compare them with counts and check coverage warnings."], note: "Enter new closing counts in Closing update; add arrived stock through a delivery receipt." },
  { area: "Daily operations · Sales", title: "Report sales during service", href: "/workspace/sales", items: ["Record a complete sales interval, or correct an earlier report. Omitted dishes mean zero sales.", "Reported sales, Ingredient usage, Stock estimates and Sales assessment separate facts from calculated findings."], note: "Recipe-based usage is not a physical count. This is sales reporting, not an automatic external POS connection." },
  { area: "Daily operations · Forecast & projections", title: "Look ahead using stored calculations", href: "/workspace/calculations", items: ["Select an assessment to inspect its stored demand forecast, ingredient balances and shortages.", "Compare existing commitments with hypothetical recommendation additions; check scope, freshness and exact values."], note: "Outputs appear only when a calculation has been persisted. Missing or incomplete results are not proof that stock is safe." },
  { area: "Daily operations · Closing update", title: "Finish the day with observed facts", href: "/workspace/daily", items: ["Enter final dish sales and the physical count for each batch. Save a draft before submitting.", "Correct a previous submission and inspect submission history and reconciliation."], note: "Closing counts already include received stock. Do not subtract the day's sales from those counts again." },
  { area: "Purchasing · Recommendations", title: "Review before approving", href: "/workspace/recommendations", items: ["Review quantities, suppliers, arrival times and costs; open reasoning, evidence and captured calculations.", "Compare versions and approve or reject the exact version. Contingency recommendations may add purchases without changing existing commitments."], note: "Approval does not place an order. The Agent must complete a feasible assessment before a new recommendation can appear." },
  { area: "Purchasing · Purchases & deliveries", title: "Record the purchase you actually arranged", href: "/workspace/deliveries", items: ["Arrange the purchase outside ReStock, then record the actual quantities and expected delivery.", "Use All, Outstanding and Closed to find purchases and inspect their change and receipt history."], note: "Recommendations and recorded purchases are separate. Avoid buying quantities that are already committed." },
  { area: "Purchasing · Purchases & deliveries", title: "Receive only what arrived", href: "/workspace/deliveries", items: ["Record a full or partial receipt with the batch expiry date. Only received stock is added to inventory.", "Report delays, shortfalls or cancellations. A partial receipt leaves the remaining quantity outstanding."], note: "A closed purchase can also have a cancelled remainder; it does not necessarily mean everything was received." },
  { area: "Activity", title: "Understand what changed and why", href: "/workspace/activity", items: ["Timeline shows operational changes. Assessments lets you request a review and follow queued, running and completed states.", "Open findings and evidence, or use Audit details to inspect actors, timestamps and record references."], note: "A completed assessment may keep the current plan or escalate an issue without creating a new recommendation." },
  { area: "Settings · Suppliers & promotions", title: "Keep changing conditions up to date", href: "/workspace/suppliers", items: ["Compare Supplier offers, view terms, and record price, availability or delivery changes.", "Create or revise Promotions, including dates, affected dishes, multipliers and active status."], note: "These changes can request assessments. An offer is not an order; a promotion multiplier is an input, not a proven forecast." },
  { area: "Settings · Suppliers & promotions", title: "Check ordering occasions and holidays", href: "/workspace/suppliers", items: ["Ordering occasions lets you mark scheduled occasions as ordered or skipped.", "Holidays provides read-only Singapore public-holiday dates and source references."], note: "Marking an occasion does not record a purchase. A holiday does not automatically close the restaurant or increase demand." },
  { area: "Settings · Menu & recipes", title: "See how dishes use ingredients", href: "/workspace/inventory?view=menu", items: ["Inspect dishes and ingredient quantities per portion.", "Recipes help explain the ingredient usage calculated from reported sales."], note: "This is read-only reference data, not a menu or recipe editor." },
  { area: "Settings · Ordering schedules", title: "Know when to consider buying", href: "/workspace/inventory?view=schedules", items: ["Read each ingredient's ordering interval and starting date.", "Your usual workflow: report sales → review a recommendation → arrange and record purchases → receive stock → submit closing counts."], note: "Schedules are read-only. A scheduled occasion does not mean stock must be purchased. Replay this tour anytime using Workspace tour." },
] as const;

export const tourStorageKey = (username: string) => `restock:workspace-tour:v1:${encodeURIComponent(username)}`;
