"""Seeded catalog inventory and manager sessions"""

import sqlalchemy as sa
from alembic import op

revision = "357269117e91"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "holidays",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("source_url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("date"),
    )
    op.create_table(
        "ingredients",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.CheckConstraint("unit IN ('kg', 'litres', 'pieces')"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "manager_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_table(
        "menu_items",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "suppliers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inventory_lots",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("ingredient_id", sa.String(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=False),
        sa.Column(
            "initial_quantity", sa.Numeric(precision=12, scale=3), nullable=False
        ),
        sa.CheckConstraint("initial_quantity >= 0"),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recipes",
        sa.Column("menu_item_id", sa.String(), nullable=False),
        sa.Column("ingredient_id", sa.String(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.CheckConstraint("quantity > 0"),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["menu_item_id"],
            ["menu_items.id"],
        ),
        sa.PrimaryKeyConstraint("menu_item_id", "ingredient_id"),
    )
    op.create_table(
        "supplier_offers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("supplier_id", sa.String(), nullable=False),
        sa.Column("ingredient_id", sa.String(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "available_quantity", sa.Numeric(precision=12, scale=3), nullable=True
        ),
        sa.Column("moq", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("pack_size", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("lead_time_minutes", sa.Integer(), nullable=True),
        sa.Column("order_cutoff", sa.JSON(), nullable=False),
        sa.Column("feasible_delivery_at", sa.JSON(), nullable=True),
        sa.Column("current_status", sa.String(), nullable=False),
        sa.Column(
            "recent_on_time_rate", sa.Numeric(precision=5, scale=4), nullable=True
        ),
        sa.Column("shelf_life_days_on_arrival", sa.Integer(), nullable=True),
        sa.Column("delivery_fee_sgd", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "emergency_fee_sgd", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("current_status IN ('AVAILABLE', 'UNAVAILABLE', 'UNKNOWN')"),
        sa.CheckConstraint("delivery_fee_sgd >= 0 AND emergency_fee_sgd >= 0"),
        sa.CheckConstraint(
            "lead_time_minutes >= 0 AND shelf_life_days_on_arrival >= 0"
        ),
        sa.CheckConstraint("recent_on_time_rate BETWEEN 0 AND 1"),
        sa.CheckConstraint(
            "unit_price >= 0 AND available_quantity >= 0 AND moq >= 0 AND pack_size > 0"
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("supplier_id", "ingredient_id"),
    )
    op.create_table(
        "stock_counts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("lot_id", sa.String(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("counted_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("quantity >= 0"),
        sa.ForeignKeyConstraint(
            ["lot_id"],
            ["inventory_lots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lot_id", "counted_at"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stock_counts")
    op.drop_table("supplier_offers")
    op.drop_table("recipes")
    op.drop_table("inventory_lots")
    op.drop_table("suppliers")
    op.drop_table("menu_items")
    op.drop_table("manager_sessions")
    op.drop_table("ingredients")
    op.drop_table("holidays")
    # ### end Alembic commands ###
